### ISSUE TITLE
tagme() rejecting login

### ISSUE THREAD

**Issue by zcrysler** [jbrzusto/TO_DO#134] opened 2017-11-07 16:38 UTC
I haven't been able to login through the motus R package to access the tagme() function since sometime on Friday - I get the error "The motus data server rejected your login credentials"

**Comment by zcrysler** [comment] 2017-11-07 17:22
Strange - it's working for me now too.  I had tried it a bunch of times earlier with no success so whatever the reason restarting the data server seemed to have solved the problem!

**Comment by jbrzusto** [comment] 2017-11-14 13:19
reopening:  the problem is due to server connections lapsing.
the `authenticate_user` API was not properly checking for this, because iit doesn't go through
`validate_request()`

**Comment by jbrzusto** [comment] 2017-11-14 13:28
closing in deference to jbrzusto/motusServer#281

**Closed by jbrzusto** 2017-11-14 13:28 UTC
